abstract: ~
author: KAN Fushihara <kan at mobilefactory dot jp>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Sledge-SessionManager-MobileID
no_index: 
  directory: 
    - inc
    - t
version: 0.01
